### ISSUE TITLE
Custom picker?

### ISSUE THREAD

**Issue by amanzan** [philliphsu/BottomSheetPickers#10]
Is it possible to create a picker with custom data, meaning something different from Date or Time?

**Comment by philliphsu** [comment]
For what use?

**Comment by amanzan** [comment]
It would be like the second Date Picker screenshot, but instead of years, a custom list of String values. Similar to an iOS selector but "Materialized" :)

Also it would be great to be able to customize the header

**Comment by philliphsu** [comment]
The use case for that sounds specific to your app. It's simple enough to create your own solution using a standard list and adapter.
