### ISSUE TITLE
Custom Date Selection Combinations

### ISSUE THREAD

**Issue by ersin-ertan** [philliphsu/BottomSheetPickers#16]
Feature Request:
The ability to select individual elements ex. day, month, year
without including the selection or display of other elements.

Pick and choose  combinations of elements to select and in which order ex. month-year, day-month.

**Comment by philliphsu** [comment]
As to your first request, I'm not sure if that is practical. Any valid date depends on all three parts. You can't individually select day=30 for month=FEBRUARY, for instance. Or individually select year=2017 for month=FEBRUARY and day=29. Previous selections have to be adjusted if the current selection makes the rest of the date invalid.

If I understand the second request correctly, you can already manipulate the elements in any combination and order you wish.

**Comment by ersin-ertan** [comment]
The second request was an extension of the first, requesting what your first example said was not possible. I see what your getting at with the leap year, and misaligned selection combinations.
