### ISSUE TITLE
Update support library

### ISSUE THREAD

**Issue by zarulizham** [philliphsu/BottomSheetPickers#20]
Can you update your support library? If not it will trigger warning below:

>All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.3.1, 25.1.0. Examples include com.android.support:animated-vector-drawable:25.3.1 and com.android.support:gridlayout-v7:25.1.0 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)

My build.gradle:

    dependencies {
        compile('com.philliphsu:bottomsheetpickers:2.3.2') {
            exclude group: 'com.android.support', module: 'appcompat-v7'
            exclude group: 'com.android.support', module: 'design'
        }

        compile fileTree(include: ['*.jar'], dir: 'libs')
        compile 'com.android.support:design:25.3.1' // here is the warning
        compile 'com.android.volley:volley:1.0.0'
        compile 'com.android.support:appcompat-v7:25.3.1'
        compile 'com.android.support:cardview-v7:25.3.1'
        compile 'me.angrybyte.picker:picker:1.2.0'
        compile 'com.github.bluejamesbond:textjustify-android:2.1.6'
        compile 'com.android.support.constraint:constraint-layout:1.0.2'
        compile 'com.github.JakeWharton:ViewPagerIndicator:2.4.1'
        compile 'com.android.support:support-v4:25.3.1'
        compile 'com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1'
        compile 'com.jakewharton:butterknife:8.5.1'
        compile 'org.greenrobot:eventbus:3.0.0'
        compile 'org.greenrobot:greendao:3.2.0'
        testCompile 'junit:junit:4.12'
    }

**Comment by philliphsu** [comment]
Try excluding the `gridlayout-v7` library as well and add that to your own project's dependencies.

**Comment by zarulizham** [comment]
I've added `gridlayout-v7` in my own dependencies and exclude it in this library. Seems there's no warning anymore. Thank you 👍
