### ISSUE TITLE
Error: Year end must be larger than year start

### ISSUE THREAD

**Issue by zarulizham** [philliphsu/BottomSheetPickers#22]
Hi, I need to set minDate and maxDate, but getting error `java.lang.IllegalArgumentException: Year end must be larger than year start`

Here is my implementation:

    Calendar now = Calendar.getInstance();

    DatePickerDialog.Builder dialog = new DatePickerDialog.Builder(CalculatorActivity.this,
            now.get(Calendar.YEAR), now.get(Calendar.MONTH), Calendar.DAY_OF_MONTH);
    dialog.setMaxDate(now);
    dialog.setMinDate(minDate);
    Log.e("Max", now.getTime().toString());
    Log.e("Min", minDate.getTime().toString());

    DatePickerDialog dp = dialog.build();
    dp.show(getSupportFragmentManager(), "end");

As logcat show:
> E/Max: **Thu May 04 04:08:35 GMT+00:00 2017**<br>
 E/Min: **Wed Feb 01 04:08:33 GMT+00:00 2017**
 
 So, how can I achieve this without error?

Edit:
In DatePickerDialog.java in your library, I think this line (line 605) need to change to `endYear < startYear` instead of below

    public void setYearRange(int startYear, int endYear) {
        if (endYear <= startYear) {
            throw new IllegalArgumentException("Year end must be larger than year start");
        }
        mMinYear = startYear;
        mMaxYear = endYear;
        if (mDayPickerView != null) {
            mDayPickerView.onChange();
        }
    }

**Comment by philliphsu** [comment]
Issue has been acknowledged. `setMinDate()` and `setMaxDate()` should not be calling `setYearRange()`.

**Comment by zarulizham** [comment]
Thank you sir. Waiting for your release 👍

**Comment by philliphsu** [comment]
Fixed in v2.3.3.

**Comment by zarulizham** [comment]
Thank you 🥇
