### ISSUE TITLE
Calendar returns wrong day

### ISSUE THREAD

**Issue by vexonius** [philliphsu/BottomSheetPickers#24]
Hello,

I think this isn't a library problem, but I'm having problem with this for days. I'm trying to get specific days in a week when a user selects a date in onDateSet method, but I constantly get wrong values

`Calendar kal = Calendar.getInstance();
        kal.set(Calendar.YEAR, year);
        kal.set(Calendar.MONTH, monthOfYear);
        kal.set(Calendar.DAY_OF_MONTH, dayOfMonth);

        DateFormat sday = new SimpleDateFormat("dd");
        DateFormat smonth = new SimpleDateFormat("MM");
        DateFormat syear = new SimpleDateFormat("yyyy");

        kal.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);

        String mMonth = smonth.format(kal.getTime());
        String mDay = sday.format(kal.getTime());
        String mYear = syear.format(kal.getTime());

        Toast.makeText(getContext(), "Ponediljak: " + mMonth + " " + mDay + " " + mYear, Toast.LENGTH_SHORT).show();`

Toast shows the date of monday of the current week, not the selected one. What am I doing wrong? Can you be kind and help me? Thanks

**Comment by philliphsu** [comment]
Why are you calling `kal.set(Calendar.DAY_OF_WEEK, Calendar.MONDAY);`?

**Comment by vexonius** [comment]
I'm trying to get the monday of that week

**Comment by philliphsu** [comment]
After
```
kal.set(Calendar.YEAR, year);
kal.set(Calendar.MONTH, monthOfYear);
kal.set(Calendar.DAY_OF_MONTH, dayOfMonth);
```
you should call `kal.get(DAY_OF_WEEK)` which is a value from SUNDAY (1) to SATURDAY (7). MONDAY is 2. To get the Monday in the same week as the selected day, call `kal.add(DAY_OF_MONTH, diff)` where `diff = - (kal.get(DAY_OF_WEEK) - MONDAY)`. So if you selected a Wednesday, the Monday of that same week is two days behind. Thus, `diff = -(WEDNESDAY - MONDAY) = -(4-2) = -2`. `kal` is now set to the Monday of that week.

**Comment by vexonius** [comment]
Thank you so much. You saved me from days of searching for solution. Now it finally works. And the library is great and good looking! You can close this thread.
