### ISSUE TITLE
12 hour time error

### ISSUE THREAD

**Issue by haxzie** [philliphsu/BottomSheetPickers#25]
Returns 24 hour time for 12 hour time. Hours in chosen in 12 hour format are always in 24 hours format (ie. Even i choose 1:30 am it returns 13:30)

**Comment by philliphsu** [comment]
This is working as intended. It is easier to work with 24 hour times when
working with machines. It is only important to distinguish between time
formats when displaying the time to a human. There are various Java APIs
that handle the difference in time format for you when you're displaying
the time.

**Comment by zarulizham** [comment]
You can use `SimpleDateFormat` to change the date/time format
