### ISSUE TITLE
Override dialog style

### ISSUE THREAD

**Issue by ZaydelEduard** [philliphsu/BottomSheetPickers#5]
How i can set my own style? 
dialog.setStyle(DialogFragment.STYLE_NORMAL, R.style.MyOwnStyle);  - not working.

**Comment by philliphsu** [comment]
Currently there are no options for custom theming.

**Comment by ZaydelEduard** [comment]
You are planing add this option for custom theming?

**Comment by philliphsu** [comment]
I had plans for customized colors, but that won't be a priority. Using the accent color that you define should be sufficient for now. What are you looking to customize?

**Comment by ZaydelEduard** [comment]
Thanks for replaing. Problem is resolved.
