### ISSUE TITLE
Cancelable bottom sheet date picker dialog

### ISSUE THREAD

**Issue by borhammere** [philliphsu/BottomSheetPickers#9]
`dialog.isCancelable = true`
But I can't cancel dialog only choose a day, back button or pressing out of the dialog not working.

P.S. thanks for this pretty picker!

**Comment by philliphsu** [comment]
This is intentional behavior so that you can scroll in the picker. Otherwise, vertical swiping would swipe the bottom sheet down. I am looking into alternative interactions for a future release.

**Comment by borhammere** [comment]
Thank! I would glad to have back button logic =)

**Comment by amanzan** [comment]
Yes, a cancel button or something like that would be great!

**Comment by philliphsu** [comment]
Cancel button added in version 2.0.3. Cancelling via back button and outside tapping will be in a future release.

**Comment by philliphsu** [comment]
Cancelling via back button and outside tapping is now available in version 2.1.1. However, please note this does not yet apply to the year picker as well.

**Comment by philliphsu** [comment]
The date picker can now be dismissed while in the year picker without affecting vertical scrolling. Please update to version 2.2.0 and try it out.

As of this update, all cancel/dismiss functions have been restored to the date picker. If there are no further problems, this issue will be closed.
